# Site settings
title: Jordan Rosenblum
#email: jmrosen155@gmail.com
description: Commerce Data Scientist at American Express
github_username:  jmrosen155
linkedin_username:  jordanrosenblum
email_username:  jmrosen155

# Build settings
markdown: kramdown
