# Site settings
title: Jordan's Github Page
#email: jmrosen155@gmail.com
description: Data Science MS student at Columbia University
github_username:  jmrosen155
linkedin_username:  jordanrosenblum

# Build settings
markdown: kramdown
