# Site settings
title: Jordan's Homepage
#email: jmrosen155@gmail.com
description: Data Science MS student at Columbia University
github_username:  jmrosen155
linkedin_username:  jordanrosenblum
email_username:  jmrosen155

# Build settings
markdown: kramdown
