# Site settings
title: Jordan Rosenblum
#email: jmrosen155@gmail.com
description: Senior Data Scientist at iHeartRadio Digital
github_username:  jmrosen155
linkedin_username:  jordanrosenblum
email_username:  jmrosen155

# Build settings
markdown: kramdown
